import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import './globals.scss';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ToastContainer } from 'react-toastify';
import Provider from '@/utils/Provider';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={montserrat.className}>
				<Provider>
					<AntdRegistry>
						{children}
						<ToastContainer />
					</AntdRegistry>
				</Provider>
			</body>
		</html>
	);
}
